### ISSUE TITLE
Create a color ramp legend

### ISSUE THREAD

**Issue by claustres** [kalisio/kMap#15]
It should allow to display the color map used and to switch between multiple units. Not sure if it will be useful to stack legends for different layers at the same time, the last active one should be sufficient. https://www.windy.com/?43.217,2.350,5 provides a great example.
* [x] update layer descriptions to include relevant units for each variable
* [x] the input color ramp should be specified using https://github.com/gka/chroma.js/
* [x] unit conversion should rely on http://mathjs.org/docs/datatypes/units.html

**Comment by claustres** [comment]
Requires to update layer descriptions to include relevant units for each variable.

**Comment by claustres** [comment]
The input color ramp should be specified using https://github.com/gka/chroma.js/.

**Comment by claustres** [comment]
Unit conversion should rely on http://mathjs.org/docs/datatypes/units.html.

**Comment by claustres** [comment]
Linked to https://github.com/weacast/weacast-leaflet/issues/2

**Comment by leob** [comment]
This is now committed on master. Items still to look at:

- Add an option (prop?) to generate a smooth gradient instead of color steps
- Try with a "horizontal" variant of the color legend (at the top of the screen/map)
- After selecting a different forecast model, we may have to update the color legend?
  (unit values/colors may change?)
- Unit conversion - we now have one unit "knot" hardcoded (see TODO in the legend mixin) -
   what do we do with that?

**Comment by claustres** [comment]
Horizontal version is nice to have for now. 

Knot unit can remain hard coded since it is just a unit not available by default in mathjs the app requires. It's really app specific.

**Comment by leob** [comment]
Fixed the last few bugs, I think this component is finished for now.
