### ISSUE TITLE
Provide a layer to draw a gradient path in map

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kMap#77]

**Comment by claustres** [comment]
Ideally this feature should integrate smoothly with GeoJson layers, ie we should create a specific layer handling it under-the-hood so that we can also benefit from the realtime interface, popups, tooltips, etc.

Maybe it is sufficient to return this type of layer in the [updateFeature() function](https://github.com/kalisio/kMap/blob/master/src/client/mixins/map/mixin.geojson-layers.js#L22) whenever the relevent properties are found on the feature.

**Comment by claustres** [comment]
Maybe better to make it work at GeoJson layer level like for geodesic arcs: see https://github.com/kalisio/kMap/blob/master/src/client/mixins/map/mixin.geojson-layers.js#L9.
